### ISSUE TITLE
Create 1.1.0 ooniprobe-android release

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooniprobe-android#36]
I am going to make a checklist of some of the things we should be sure to address before we make the release:

* [x] Address pending critical bugs

* [ ] -Change the icon to the rounded box icon as in the ios version-

* [ ] Update link to NDT description to the published page on the website

* [ ] Update to latest version of measurement-kit

* [ ] Create ChangeLog and write in Changelog how all versions < 1.1.0 contained the `measurement_kit` string instead of `ooniprobe-android` and note the measurement_kit and ooni-wui version

* [ ] Update to the latest version of the ooni-wui (https://github.com/TheTorProject/ooni-wui/releases/download/v2.2.0-rc.0/ooni-wui.mobile.2.2.0-rc.0.zip)

* [ ] Tag and sign release 1.1.0

* [ ] Upload to Android Market 🎉
